### ISSUE TITLE
Updated Hush Binaries for 1.0.12

### ISSUE THREAD

**Issue by madbuda** [vaklinov/hush-swing-wallet-ui#13]
https://github.com/madbuda/hush/releases/tag/v1.0.12

https://github.com/MyHush/hush/tree/v1.0.12-rc

I've tested these on windows extensively, I would update and do a PR but I haven;t had time to dig into swing wallet to see what changes need to be made.

**Comment by leto** [comment]
@vaklinov let us know if you run into issues

**Comment by vaklinov** [comment]
I am not currently working on the HUSH GUI wallet actively... If you wish, you can take my latest release and replace only the HUSH binaries in it: https://github.com/vaklinov/hush-swing-wallet-ui/blob/master/docs/Release_0.68.6.md

**Comment by macdaddyillness** [comment]
As of today my GUI wallet is giving me a a error code says a general unexpected error has occurred couldn't connect to server:eof reached code 1 make sure server is running and you are connected to rpc port see the console output for more detailed information! How can I fix this and not lose my hush I've already collected any help is appreciated and thanks for your time

**Comment by madbuda** [comment]
Head over to myhush.org and download the new wallet

**Comment by vaklinov** [comment]
@macdaddyillness  It seems your HUSH daemon is not starting properly. The log file %APPDATA%\Hush\debug.log may reveal more information about the reason. You may also try to run hushd.exe manually before you start the GUI wallet.

**Comment by madbuda** [comment]
I'm closing this as we have a maintained version in our repo
