### ISSUE TITLE
Unexpected critical error com.eclipsesource.json.ParseException: Expected value at 1:1

### ISSUE THREAD

**Issue by Pcenginefx** [vaklinov/hush-swing-wallet-ui#3]
This is a clean install - at the "Verifying proving key..." I get the following error (see attached)
Running Windows 10 Pro.

![error](https://user-images.githubusercontent.com/13955031/27461885-aeafd2fe-5771-11e7-8cd2-c4edc2ce063e.png)

**Comment by vaklinov** [comment]
Please specify which release you are running. If using release 0.68.3-beta you need to create the file `hush.conf` manually. In any case please attach the log file `%LOCALAPPDATA%\HUSHSwingWalletUI\HUSHWallet_2017_6_debug.log` for analysis...

**Comment by Pcenginefx** [comment]
Ah, ok - yes...I created the hush.conf file but didn't actually name it that (it was named hush.txt). After I renamed it to hush.conf I no longer get the error and the wallet loads correctly. Thanks!
