### ISSUE TITLE
hushd deletes

### ISSUE THREAD

**Issue by oblox** [vaklinov/hush-swing-wallet-ui#7]
First run on 0.68.6 on win7 64 bit, extracted to local C: drive. Double-click on HUSHSwingWalletUI, cmd prompt opens with hushd (daemon), after about 5-10 seconds, it exits and the hushd file in the local folder no longer exists (as if it deletes itself).

The wallet never loads and I'm prompted with a critical error, couldn't connect to server: EOF reached (code 1) - Make sure server is running and you are connected to the correct RPC port

There is a conf file with all the addnodes in my appdata folder. Tried deleting the local directory multiple times but same error. Wallet never loads.
![eof reached](https://user-images.githubusercontent.com/11541218/28148503-aec6c352-674c-11e7-9b94-e7e8692c6caa.png)
![hushwallet](https://user-images.githubusercontent.com/11541218/28148502-aec437c2-674c-11e7-8214-92e201226afb.png)

Other Zcash related wallets (ex. Zen) do not have this issue. How do I resolve?

**Comment by vaklinov** [comment]
The described behaviour is very strange:
1. The hushd.exe cmd prompt should not show up - it should stay hidden. I have never seen it pop up before.
2. hushd.exe should not disappear/be deleted - the GUI wallet does not delete it. Thus is very suspicious... of something wrong or maybe tampered with.

As s start please confirm that you downloaded this release:
https://github.com/vaklinov/hush-swing-wallet-ui/blob/master/docs/Release_0.68.6.md
and that you verified the SHA256 sum of the zip:
```
c633a6e4067e7bb7a9438c93621b8a2cfb5b5076ac2cda3401244128586a925e  HUSH_Wallet_0.68.6_Windows_release.zip
```
If the exact release is confirmed, then I would like to see what errors may exist in your files:
%APPDATA%\Hush\debug.log
and
%LOCALAPPDATA%\HUSHSwingWalletUI\HUSHWallet_xxxxx_debug.log

Could you please attach these files...

**Comment by oblox** [comment]
Yes, the release downloaded from there ties out with the sha256 hash. There isn't a debug.log in the appdata folder, but there is one in localappdata and is listed below:
![hushwallethash](https://user-images.githubusercontent.com/11541218/28165544-d034165a-6799-11e7-8f72-3772a45374f9.JPG)

> =================================================================================
= New log started at: Wed Jul 12 21:52:48 CDT 2017
=================================================================================

Starting HUSH Swing Wallet ...
OS: Windows 7 = WINDOWS
Current directory: C:\HUSH
Class path: C:\HUSH\HUSHSwingWalletUI.jar
Environment PATH: C:\Program Files\Broadcom\Broadcom 802.11;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\PuTTY\
Using HUSH utilities: hushd: C:\HUSH\hushd.exe, hush-cli: C:\HUSH\hush-cli.exe
hushd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if hushd is already running...
Splash: hushd will be started...
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:449)

>

I'm stumped.

**Comment by vaklinov** [comment]
Does the problem with the disappearing `hushd.exe` happen every time? Please try the following: make sure `hushd.exe` exists and first start manually `hushd.exe` from a cmd console... without starting the GUI wallet. Then observe if a debug log appears in %APPDATA%\Hush\ ... Then if `hushd.exe` starts as expected, continues working for 1-2 min, does not disappear as a file, produces a debug.log etc, only them start the GUi wallet HUSHSwingWalletUI.exe ... I am also surprised by this behaviour...

**Comment by vaklinov** [comment]
To recap: if the problem with the disappearing/deleting `hushd.exe` (very wierd) is repeatable, please try to ascertain when exactly it happens:
1. When you start `hushd.exe` from command line? or
1. When you start `hush-cli getinfo` from command line after that? or
1. When you start `HUSHSwingWalletUI.exe` after that

**Comment by oblox** [comment]
Closing this out. Turns out following your logic and running it from cmd, I can instantly see avast is cyberlocking it so it closes, then avast dumps it into the virus chest. Putting an exclusion, the gui works fine. Sorry I didn't think to check my antivirus software. Strange that it would grab ahold of the hush daemon but not the zcash or zencash one. Thanks again for being so prompt and helping with the troubleshoot.
