### ISSUE TITLE
Can't open gui wallet under ubuntu

### ISSUE THREAD

**Issue by proton2000** [vaklinov/hush-swing-wallet-ui#8]
Hello!

GUI Wallet is working correctly than now I can't open no more.

 error message: couldn't connect to server: unknow (code -1)
make sure server is running and you are connecting to the correct RPC

I didn't touch anything

Do you what is wrong?

Thanks! excuse my poor english

**Comment by vaklinov** [comment]
It appears your hushd server is not running. The reason why it happens needs to be investigated. As a start please specify what OS you have... what version of HUSH/the GUI wallet etc.

For a test please try to run hushd manually from a console to see if it starts and does not crash...

**Comment by proton2000** [comment]
Hello!
Thats ok under Ubuntu in Vm noproblem thanks!
I reinstalled hush and all is ok
